### ISSUE TITLE
Unable to import into Android Studio

### ISSUE THREAD

**Issue by KCRaju** [j4velin/Pedometer#82]
Hi i am unable to import this project into Android studio.
I am getting this issue.

![image](https://cloud.githubusercontent.com/assets/19387783/15539484/6c97c8ec-22a0-11e6-814e-15c50a244e65.png)

If i comment key.properties it is showing error in next line
![image](https://cloud.githubusercontent.com/assets/19387783/15539524/a953aea4-22a0-11e6-89e7-c9e954a12914.png)

After i comment those both lines it is showing 
![image](https://cloud.githubusercontent.com/assets/19387783/15539551/cc788e7c-22a0-11e6-8fb2-be2fcd8e5fe3.png)

But if i try down load it is showing "packages Unavailable"
![image](https://cloud.githubusercontent.com/assets/19387783/15539576/efd15462-22a0-11e6-8d95-19cdd6afc147.png)

i done manually like http://i.stack.imgur.com/AP9LZ.png

after that also i am getting error like below
![image](https://cloud.githubusercontent.com/assets/19387783/15539776/f88853fc-22a1-11e6-8127-a80c6972d6e6.png)

Even i am getting this error
![image](https://cloud.githubusercontent.com/assets/19387783/15540220/d9464b8c-22a3-11e6-973b-d3904d82c651.png)

**Please help me to resolve this issue**

**_## If possible please share eclipse source code.
I am very new to Android Studio. :(_**

**Comment by j4velin** [comment]
The first errors are due to the key.properties file not available on your device. That makes sense, as there are my private keys in it. You should use the provided key.properties.sample file and put your keys in it. The other issues seem to be related to the fact that you only search locally for those repositories and not on jcenter.
Sorry, but I use only AS for Android development and therefore won't provide a separate eclipse project.
